### PR TITLE
Include external PyPi servers

### PR DESCRIPTION
**Pull request by Sibyx**
Hello, I have created a feature for including external PyPi indexes if it's required (`-s, --sources` flag) and if they are present in `Pipfile` or `Pipfile.lock`. 

By default, I skip `pypi.org` and only extra indexes will be appended to the end of the result:

```
...
cssmin
jsmin
flask-whooshee
--extra-index-url=https://pypi.example.com/simple
```

I extended test to cover this feature, but I have to recreate all the previous test files (I am not that sure about that).

Also, I have increased library version to `0.2.0`.

Thank you very much for such a handy tool!

### CODE REVIEW

**Review by frostming — COMMENTED** [review]
I reviewed the changes, just one point.
What about the PyPI sources, you just discarded them, but what if the source is not pypi.org?

**Comment by Sibyx** [comment]
That's pretty good question. I have been unsure about the correct solution for default PyPi source. Do you have any ideas?

**Comment by frostming** [comment]
@Sibyx I'd expect to convert the pypi source into a `-i/--index-url` line in requirements.txt.

**Comment by frostming** [comment]
Thanks again, will cut a release shortly.

**Pull request merged**
